In [14]:
import numpy as np

def find_submatrix(big_mat: np.ndarray, small_mat: np.ndarray)->np.ndarray:
    
    if small_mat.ndim > big_mat.ndim:
        return np.empty
    
    #find instances where corner of small matrix exists in large matrix
    candidates = np.where(big_mat==small_mat[0][0])
    #reorganise array such that each element contains coordinates for 1 point
    candidates = np.transpose(candidates)
    print(candidates, len(candidates))

    size = small_mat.shape
    print(size)
    #prepare a list to contain n-dimensional slices for a candidate
    dim = [None]*len(candidates[0])
    print(dim)

    location_list = []
    #for each candidate coordinate
    for i in range(len(candidates)):
        #for each dimension
        for j in range(len(dim)):
            dim[j] = slice(candidates[i][j], candidates[i][j]+size[j])
            print(dim)

        #slice large matrix at candidate coordinates to obtain same size sub matrix as small matrix to compare using np.all()
        test_mat = big_mat[dim]
        print(test_mat)
        if (np.all(test_mat==small_mat)):
            location_list.append(candidates[i])
            
    return np.array(location_list)

In [15]:
big_mat = np.array([[5,2,5], [4,5,6], [7,8,9]])
small_mat = np.array([[5,6], [8,9]])
find_submatrix(big_mat, small_mat)

[[0 0]
 [0 2]
 [1 1]] 3
(2, 2)
[None, None]
[slice(0, 2, None), None]
[slice(0, 2, None), slice(0, 2, None)]
[[5 2]
 [4 5]]
[slice(0, 2, None), slice(0, 2, None)]
[slice(0, 2, None), slice(2, 4, None)]
[[5]
 [6]]
[slice(1, 3, None), slice(2, 4, None)]
[slice(1, 3, None), slice(1, 3, None)]
[[5 6]
 [8 9]]


C:\Users\ETCH\AppData\Local\Temp\ipykernel_8356\1241051870.py:29: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  test_mat = big_mat[dim]


array([[1, 1]], dtype=int64)